In [ ]:
import numpy as np

In [10]:
x = np.random.randint(0,10,size=10)
x

array([4, 3, 6, 1, 3, 9, 0, 8, 5, 9])

In [11]:
w = np.random.randint(0,10,size=10)
w

array([5, 0, 8, 6, 0, 8, 0, 8, 8, 0])

In [12]:
b = np.random.randint(0,10,size=10)
b

array([9, 5, 1, 2, 9, 6, 1, 3, 1, 0])

In [15]:
f = np.add(sum(np.multiply(x,w)),b)
f

array([259, 255, 251, 252, 259, 256, 251, 253, 251, 250])